### ISSUE TITLE
[lamachine2] Please help test the LaMachine v2 release!

### ISSUE THREAD

**Issue by proycon** [proycon/LaMachine#61]
This is a LaMachine issue intended for *you* (yes, you!), the reader:

LaMachine 2 has been released. Though there are still a few loose ends to tie (see https://github.com/proycon/LaMachine/milestone/1), I would like to request some volunteers to give it a try on their system.

Please follow the installation instructions on the new LaMachine website:
  https://proycon.github.io/LaMachine

or from the README:
  https://github.com/proycon/LaMachine/blob/master/README.md  

Excerpt of installation instructions to get started immediately:
> To build your own LaMachine instance, in any of the possible flavours, or to download a pre-built image, open a terminal on your Linux, BSD or Mac OS X system and run the following command:
> 
> bash <(curl -s https://raw.githubusercontent.com/proycon/LaMachine/master/bootstrap.sh)
> 
> This will prompt you for some questions on how you would like your LaMachine installation and allows you to include precisely the software you want or need and ensures that all is up to date.

If everything works, please mention in a comment your platform and the flavour/version of LaMachine you installed. If it doesn't work, mention what went wrong. If I have enough independent confirmations on a variety of systems, I can release officially. Any other feedback is welcome too. Thanks!

**Comment by kosloot** [comment]
After @proycon added some fixes, installation was successful on Ubuntu 17.10

**Comment by fkunneman** [comment]
Fatal error when installing LaMachine2 on Mac OSX:

Version: Mac OSX High Sierra, 10.13.3
Installation options: local, stable version

Log:

Setting up control environment...
 (with virtualenv and ansible inside)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/bin/virtualenv", line 7, in <module>
    from virtualenv import main
ModuleNotFoundError: No module named 'virtualenv'
================ FATAL ERROR ==============
An error occurred during installation!!
Unable to create LaMachine control environment

**Comment by proycon** [comment]
@fkunneman What version of Python is the default on your machine if you simply run "python"? The bootstrap uses the system default which is usually 2.7, but your error refers to 3.4.

**Comment by fkunneman** [comment]
The standard version is python 3.5.2: 
Python 3.5.2 |Anaconda 4.2.0 (x86_64)

**Comment by Duchadian** [comment]
Installation worked with 3.5.2 on Ubuntu 16.04 Server without problems after the .yml file fix.

Regarding the issue above, Anaconda 3.5.2 doesn't come bundled with virtualenv. Also, the python versions between the error and the anaconda install don't match. Not sure what is going on there.

**Comment by proycon** [comment]
@fkunneman The discrepancy between the python versions is a bit strange indeed as @Duchadian already remarked. I just added some checks to the bootstrap to detect if Anaconda is in the way. Can you give it a try again? 

I could use some other Mac OS X testers too (@fbkarsdorp? @antalvdb). On my own OS X VM and on travis' OS X it does work already.

**Comment by fkunneman** [comment]
@proycon just gave it a try again, and it still gives an error when calling 'virtualenv'. It appears that the path that it calls is a shell with the following lines:

#!/usr/local/bin/python3

# -*- coding: utf-8 -*-
import re
import sys

from virtualenv import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())

-----
The line 'from virtualenv import main' gives ModuleNotFoundError: No module named 'virtualenv'

**Comment by proycon** [comment]
@fkunneman And which Python is that ``/usr/local/bin/python3``? 3.4   or Anaconda's 3.5.2?

**Comment by fkunneman** [comment]
Oops! Forgot to include the path in my last comment. Herewith:

/Library/Frameworks/Python.framework/Versions/3.4/bin/virtualenv

**Comment by proycon** [comment]
@fkunneman Normally the bootstrap installs virtualenv for you, but since you already have it it doesn't do that. The one you have seems broken somehow. Can you try a ``sudo pip3 install virtualenv`` and ensure that pip3 uses the 3.4 and not anaconda?

**Comment by fkunneman** [comment]
That did the trick! New error during the installation of base packages though:

TASK [lamachine-core : Installing common base packages (Homebrew)] *****************************************
failed: [lamachine-LM2] (item=['pkg-config', 'autoconf', 'automake', 'libtool', 'autoconf-archive', 'xml2', 'libxslt', 'icu4c', 'libtextcat', 'libtar', 'python', 'wget', 'ansible', 'boost', 'boost-python3']) => {
    "changed": false,
    "item": [
        "pkg-config",
        "autoconf",
        "automake",
        "libtool",
        "autoconf-archive",
        "xml2",
        "libxslt",
        "icu4c",
        "libtextcat",
        "libtar",
        "python",
        "wget",
        "ansible",
        "boost",
        "boost-python3"
    ]
}

MSG:

/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- mach (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/Homebrew/extend/pathname.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/Homebrew/global.rb:3:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/brew.rb:15:in `<main>'

PLAY RECAP *************************************************************************************************
lamachine-LM2              : ok=8    changed=5    unreachable=0    failed=1

======================================================================================
Building a local LaMachine environment has failed unfortunately. You have several options:
 - Start from scratch again with a new bootstrap, possibly tweaking configuration options
 - Attempt to activate the environment (run: lamachine-LM2-activate) and debug the problem
 - Run lamachine-LM2-update after activating the environment to see if the problem corrects itself
 - File a bug report on https://github.com/proycon/LaMachine/issues/
   The log file has been written to /Users/fkunneman/code/lamachine-controller/LM2/LaMachine/lamachine-LM2.log

**Comment by proycon** [comment]
Maybe your homebrew got broken after an OS X update? Does it still work when you do a ``homebrew update``. See also https://stackoverflow.com/questions/24652996/homebrew-not-working-on-osx

**Comment by fkunneman** [comment]
It worked! Hooray

**Comment by proycon** [comment]
Released first v2 release with two Ubuntu confirmations, two Mac OS X confirmations. More testing still welcome of course!

**Comment by ErkanBasar** [comment]
**Summary:** Fatal permission error during installation of _Ansible_. 

**LaMahine Installation:** Development version in a local user environment

**OS:** Linux Mint 18.2 Cinnamon 64 bit
**Kernel:** 4.15.11

**Last words before it died**:
```
Do you have administrative access (root/sudo) on the current system? [yn] y
Looking for dependencies...
/usr/bin/git
/bin/nano
 Missing dependencies: ansible
Ansible is required for LaMachine but not installed yet. Install now?
Run: sudo echo 'deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main' >> /etc/apt/sources.list && sudo apt-get  update && sudo apt-get  install ansible ? [yn] y
/dev/fd/63: line 728: /etc/apt/sources.list: Permission denied
================ FATAL ERROR ==============
An error occurred during installation!!
Ansible installation failed
===========================================
```

**Installation with sudo:**
```
$ sudo bash <(curl -s https://raw.githubusercontent.com/proycon/LaMachine/master/bootstrap.sh)
[sudo] password for <username>:  (correct password given)
bash: /dev/fd/63: No such file or directory
```

**Comment by proycon** [comment]
Thanks! I took Linux Mint into consideration explicitly, but haven't tested it myself yet.
So it didn't ask for sudo during that step? Which I guess means you already entered it a bit earlier in the processed and it was cached? I don't really know why this didn't work (it does on debian), but I suppose I can better choose more ubuntu-like behaviour for Linux Mint and use ``apt-add-repository``. I have updated the bootstrap, can you try again?

**Comment by ErkanBasar** [comment]
`apt-add-repository` worked, Ansible is installed. However, it failed at another point. See below for details.

**Issue:** `libtar` not found error during configuration of `ticcutils` 

**Last words before it died:**
```

/ TASK [lamachine-cpp-automake : ticcutils - Invoke \
\ configure]                                        /
 ---------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

fatal: [lamachine-lamac]: FAILED! => {
    "changed": true, 
    "cmd": [
        "./configure", 
        "--prefix=/home/mebasar/hede/lamachine-lamac"
    ], 
    "delta": "0:00:03.891861", 
    "end": "2018-03-29 17:08:29.609313", 
    "rc": 1, 
    "start": "2018-03-29 17:08:25.717452"
}

STDOUT:

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes

.... (some more 'checking' lines)

checking libtar.h usability... no
checking libtar.h presence... no
checking for libtar.h... no

STDERR:

configure: error: libtar not found. Please install libtar.

MSG:

non-zero return code
 ____________
< PLAY RECAP >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

lamachine-lamac            : ok=35   changed=28   unreachable=0    failed=1   
======================================================================================
Building a local LaMachine environment has failed unfortunately. You have several options:
 - Start from scratch again with a new bootstrap, possibly tweaking configuration options
 - Attempt to activate the environment (run: lamachine-lamac-activate) and debug the problem
 - Run lamachine-lamac-update after activating the environment to see if the problem corrects itself
 - File a bug report on https://github.com/proycon/LaMachine/issues/
   The log file has been written to /home/mebasar/hede/lamachine-controller/lamac/LaMachine/lamachine-lamac.log
```
--------
**LaMahine Installation:** Development version in a local user environment
**OS:** Linux Mint 18.2 Cinnamon 64 bit
**Kernel:** 4.15.11

**Comment by proycon** [comment]
@ErkanBasar Did the *Installing common base packages (apt)* task complete successfully? That should have installed ``libtar-dev``. Could you send the full log otherwise? Perhaps something goes wrong in the Linux Mint detection and it skips those parts.

**Comment by asharkinasuit** [comment]
Trying to install via Windows Subsystem for Linux by invoking the magic `bash <(curl -s https://raw.githubusercontent.com/proycon/LaMachine/master/bootstrap.sh)` at the bash prompt. Using the defaults mostly: local, stable version, including Alpino but not Java and R. It seems to fail because of some error detecting the Unicode library (ICU 60); relevant part of the log:

TASK [lamachine-cpp-automake : timbl - Invoke make] ********************************************************************
fatal: [Jeroen-Latitude.localdomain]: FAILED! => {
    "changed": true,
    "cmd": [
        "make"
    ],
    "delta": "0:01:08.857492",
    "end": "2018-04-05 10:27:20.912211",
    "rc": 2,
    "start": "2018-04-05 10:26:12.054719"
}

STDOUT:

make  all-recursive
make[1]: Entering directory '/home/jeroen/lamachine2/src/timbl'
Making all in src
make[2]: Entering directory '/home/jeroen/lamachine2/src/timbl/src'
/bin/bash ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..  -I../include  -std=c++11 -W -Wall -O3 -g -pedantic -g -O2 -fopenmp -I/usr/include/libxml2 -fopenmp -I/home/jeroen/lamachine-lamachine2/include -MT Common.lo -MD -MP -MF .deps/Common.Tpo -c -o Common.lo Common.cxx
\<lots of compiler invocations\>
libtool: link: g++ -std=c++11 -W -Wall -O3 -g -pedantic -g -O2 -fopenmp -I/usr/include/libxml2 -fopenmp -I/home/jeroen/lamachine-lamachine2/include -o .libs/timbl Timbl.o  ./.libs/libtimbl.so -lxml2 -L/home/jeroen/lamachine-lamachine2/lib /home/jeroen/lamachine-lamachine2/lib/libticcutils.so -pthread -fopenmp -Wl,-rpath -Wl,/home/jeroen/lamachine-lamachine2/lib
Makefile:684: recipe for target 'timbl' failed
make[2]: Leaving directory '/home/jeroen/lamachine2/src/timbl/src'
Makefile:465: recipe for target 'all-recursive' failed
make[1]: Leaving directory '/home/jeroen/lamachine2/src/timbl'
Makefile:374: recipe for target 'all' failed


STDERR:

ar: \`u' modifier ignored since \`D' is the default (see \`U')
/home/jeroen/lamachine-lamachine2/lib/libticcutils.so: undefined reference to \`icu_60::UnicodeString::moveFrom(icu_60::UnicodeString&)'
/home/jeroen/lamachine-lamachine2/lib/libticcutils.so: undefined reference to \`icu_60::UnicodeString::append(int)'
\<many other undefined references\>
/home/jeroen/lamachine-lamachine2/lib/libticcutils.so: undefined reference to \`icu_60::UnicodeString::UnicodeString(icu_60::UnicodeString const&, int)'
collect2: error: ld returned 1 exit status
make[2]: *** [timbl] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

It looks like all the files for the ICU library are in the right places, and just to be sure I copied their latest versions (60.2) in, but it gives the same error.

Incidentally, there may be a bug in the ansible script as well because when trying multiple times, it alternately fails on the timbl and timblserver tasks. On the one run it tries to `make` timbl, which fails because of ICU but is apparently not cleaned up, then on the next run it is cleaned up but not updated, so the script continues to timblserver, which fails because timbl is not present.

**Comment by ErkanBasar** [comment]
Hi @proycon, I have tested it again today and got the same error I mentioned in [my previous comment](#issuecomment-377274273). 

In the logs I see that the installation of common base packages is skipped, but I can not see the actual reason;
```___________________________________________________
/ TASK [lamachine-core : installing common base packages \
\ (apt)]                                                 /
 --------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

skipping: [floodtags-mint] => (item=[])  => {
    "changed": false, 
    "item": [], 
    "skip_reason": "Conditional result was False"
}
```

**Full logs:** [lamachine-lama-mebasar.log](https://github.com/proycon/LaMachine/files/1879710/lamachine-lama-mebasar.log)

--------
**LaMahine Installation:** Development version in a local user environment
**Categories:** Installing all of the categories given in _install-lama.yml_
**OS:** Linux Mint 18.2 Cinnamon 64 bit
**Kernel:** 4.15.15

**Comment by proycon** [comment]
@ErkanBasar Thanks for the log, that shows the reason. My Linux Mint detection was indeed wrong. Will be fixed in the v2.1 release I'm about to do!

**Comment by proycon** [comment]
@ErkanBasar Can you try again?

**Comment by proycon** [comment]
@asharkinasuit  Thanks for testing on the windows subsystem! We didn't have any testers for that yet afaik! (sorry I missed your post earlier..)

You shouldn't need to copy anything ICU related, it should work out-of-the-box, but that being said, we had an issue with ICU 61 (#69) which should have been fixed recently, though your issue is with the previous release 60.2 .. puzzling..     

What kind of linux distribution did you install in your subsystem? Debian/Ubuntu I guess?  (otherwise Alpino won't be supported). Are you opting the development version rather than the stable version of LaMachine?

> Incidentally, there may be a bug in the ansible script as well because when trying multiple times, it alternately fails on the timbl and timblserver tasks. On the one run it tries to make timbl, which fails because of ICU but is apparently not cleaned up, then on the next run it is cleaned up but not updated, so the script continues to timblserver, which fails because timbl is not present.

Hmm, that is a good point and a bug indeed, I should take care of better clean  up in case of failure, or rather force recompilation even if it is the first installation. I'll look into it!

**Comment by TFAFKAR** [comment]
Fantastic news, humanity! Following instructions found on https://proycon.github.io/LaMachine/ for a LaMachine installation (Windows 10/2016, Own build, Ubuntu installed as Windows Subsystem) I can say I got through the entire installation process, happily accepting all default settings along the way! Flawless victory!

Well, nearly flawless. The only downside to all of this is that cpy-paste does not work at all in the terminal under windows. 10 out of 10 points for @proycon if he can patch Windows so this is fixed (a mere 9.5 out of 10 otherwise).

**Comment by asharkinasuit** [comment]
> What kind of linux distribution did you install in your subsystem? Debian/Ubuntu I guess? (otherwise Alpino won't be supported).
Yes, I have Ubuntu installed. Apparently ICU 60 was still there. I didn't realize 61 has been released as well. If I `apt-get upgrade` the icu-devtools and libicu-dev packages, it says they're already up to date. If I search for icu using aptitude, it only finds those and libicu55, so maybe those versions lag somewhat.

**Comment by proycon** [comment]
I guess libicu61 will not ship for a while on Ubuntu yet. The ``libicu-dev`` package was for 60? Perhaps uninstall the libicu55? I assume you already had that ubuntu on WSL in use for a bit prior to installing LaMachine? (because it did work out of the box for another tester as you saw)

**Comment by asharkinasuit** [comment]
I removed libicu55 and ran the install script, but it still fails with the same basic errors. I also tried installing libicu-dev anew, but that didn't work either. I've attached the complete log of my latest attempt. (git repo was already checked out but that's not the problem anyway.)
[lamachine-lm2.log](https://github.com/proycon/LaMachine/files/1890341/lamachine-lm2.log)

**Comment by kosloot** [comment]
Well, as you can see in the logfile, it directly installs icu55.
No mention of ICU 60, but maybe that is 'native' in your machine.
But it installs a lot of (old) libboost stuff, and maybe this triggers the installation of the old ICU?

just guessing

**Comment by proycon** [comment]
Actually, it seems libicu55 is the default on ubuntu 16.04. So the question is more: where did the libicu 60 come from on your system? Can you remove any icu60 installations you may have, activate your LaMachine environment, and then update your LaMachine with ``lamachine-update force=1``to force recompilation of everything?

**Comment by ErkanBasar** [comment]
Hey @proycon, the installation worked for me! 

```
ok=474  changed=282  unreachable=0    failed=0   
```
--------
**LaMahine Installation:** Development version in a local user environment
**Categories:** Installing all of the categories given in _install-lama.yml_
**OS:** Linux Mint 18.2 Cinnamon 64 bit
**Kernel:** 4.15.15

**Comment by asharkinasuit** [comment]
Sorry to be somewhat inactive on this, I have a deadline near... I found something I obtained months ago that apparently required ICU 60, so that's where that came from. I'll report back once I get that sorted out and try installing LaMachine again.

**Comment by proycon** [comment]
Of course, no problem, no rush whatsoever! :)

**Comment by ahurriyetoglu** [comment]
I got the following error on macOs High Sierra (v 10.13.3):

TASK [lamachine-register : cython - Registering metadata (lamachine-list)] ***************************************************************************************************************************************
fatal: [aliLM]: FAILED! => {
    "changed": true,
    "cmd": "#!/bin/bash\n cat /Users/alihurriyetoglu/aliLM/var/tmpmetadata.yml | /Users/alihurriyetoglu/aliLM/bin/python /Users/alihurriyetoglu/aliLM/bin/metadater.py --pip cython --yaml >> /Users/alihurriyetoglu/aliLM/var/lamachine-list.yml",
    "delta": "0:00:01.741818",
    "end": "2018-04-14 11:44:01.187195",
    "rc": 1,
    "start": "2018-04-14 11:43:59.445377"
}

STDERR:
WARNING: No translation for pip key Looking up "https
WARNING: No translation for pip key Current age based on date
WARNING: No translation for pip key Freshness lifetime from max-age
Traceback (most recent call last):
  File "/Users/alihurriyetoglu/aliLM/bin/metadater.py", line 334, in <module>
    main()
  File "/Users/alihurriyetoglu/aliLM/bin/metadater.py", line 324, in main
    parsepip(data, out.split("\n"))
  File "/Users/alihurriyetoglu/aliLM/bin/metadater.py", line 264, in parsepip
    key, value = line.split(':',1)
ValueError: not enough values to unpack (expected 2, got 1)

MSG:
non-zero return code
PLAY RECAP *******************************************************************************************************
aliLM                      : ok=59   changed=33   unreachable=0    failed=1

**Comment by proycon** [comment]
Oh!  That's from the ``develop`` branch and  shouldn't happen on the ``master`` branch! Strange, you didn't accidentally check out the development branch did you?

**Comment by proycon** [comment]
Oops, it was my fault.. the development version got released into production after a merge, I fixed it now.

**Comment by asharkinasuit** [comment]
Alrighty, I managed to "repair" ICU and recompiled LaMachine successfully. I guess that means it works on the WSL as well, as long as you haven't messed with ICU :)

Incidentally, I enabled the optional Alpino install as well, but that does not seem to work. When trying to run Alpino from the bin/ directory, it complains: 

`lm2/bin/Alpino: line 24: /home/jeroen/lm2/create_bin/Alpino.bin: No such file or directory`

I searched and the Alpino directory shows up under opt (so <lamachine root>/opt), but when I naively try to execute opt/Alpino/create_bin/Alpino.bin, another error shows:

`./Alpino.bin: error while loading shared libraries: libfadd.so: cannot open shared object file: No such file or directory`

Perhaps this is a problem with the location of the whole Alpino install, then, since the library can be found under opt/Alpino/fadd.

**Comment by proycon** [comment]
The Alpino problem reproduces indeed for me too, I'll look into it.

**Comment by egpbos** [comment]
I don't know if you intend to support zsh (i.e. running with `zsh < ..` instead of `bash < ..`), but if so, it fails for me with the following message:

```
...
Missing dependencies: pip virtualenv brew brew-cask
/dev/fd/11:585: = not found
```

I could look into it if you like.

**Comment by egpbos** [comment]
The first thing I ran into, though, was the conda incompatibility message. Is this definitely off the table, or is there a secret option to use it anyway? :) I would strongly prefer using conda to avoid another Python environment installation.

Another thing I noticed was the Homebrew dependency. Is it possible to instead use Macports?

May be a bit off topic though, I can make this another issue if you prefer.

**Comment by proycon** [comment]
Thanks for testing! I haven't tested the actual bootstrap script with ``zsh`` myself and don't really see a reason for it (extra complications), better just use ``bash`` as interpreter here, even when invoked from zsh. You can still use zsh as your main shell for LaMachine (I'm a zsh user myself too), the activation and update scripts should be compatible.

I tried going the conda route initially, but that proved to be unfeasible unfortunately as there is too much overlap between LaMachine and conda, which creates various conflicts, mainly in getting C++ libraries and software working properly; so it's definitely off the table yes. 

> Another thing I noticed was the Homebrew dependency. Is it possible to instead use Macports?

Not with LaMachine no, we had to make a choice for macOS and homebrew seemed the most obvious one. Of course you can still use macports and individually compile specific software, but you'd have to do it yourself then (not really recommended as it's a hassle and you have to know what you're doing).
